#!/bin/bash

redEcho() {
 echo -e "\e[1;31m$1\e[0m"
}

executeScriptRemotely() {
 cat $1 | ssh $2
}

scpCopy() {
 redEcho "Copying $1 to $2:$3"
 scp -q -r $1 root@$2:$3
}

yumInstall() {
 redEcho "Installing $1"
 yum -y -q install $1
}

createSshKey() {
 redEcho "Creating ssh key" 
 ssh-keygen -t rsa -P "" -f "/root/.ssh/id_rsa"
}

setupPaswordless() {
 redEcho "Setting passwordless shh to $1" 
 expect <<EOD
spawn ssh-copy-id root@$1
expect "*you want to continue*"
send -- "yes\r"
expect "*?assword:*"
send -- "$2\r"
expect eof
EOD
}

copySetupToOtherSpammers() {
 redEcho "Copying scripts and hosts file to all spammers"
 a=("$@")
 for i in "${a[@]}" ; do
  scpCopy "$BENCHMARK_FOLDER/benchmarkScripts" $i $BENCHMARK_FOLDER 
  #scpCopy "$BENCHMARK_FOLDER/benchmarkScriptsClean" $i $BENCHMARK_FOLDER 
  scpCopy "/etc/hosts" $i "/etc" 
 done
}

copySettingsToAllSpammers() {
 local SOURCE=$1
 local TARGET1=$BENCHMARK_FOLDER/benchmarkScripts/$2
 cp $SOURCE $TARGET1
 scpCopy $SOURCE $SPAMMER_LOCAL_IP_2 $TARGET1 
 scpCopy $SOURCE $SPAMMER_LOCAL_IP_3 $TARGET1 
 scpCopy $SOURCE $SPAMMER_LOCAL_IP_4 $TARGET1 
 rm -f $SOURCE
}