#!/bin/bash  
ulimit -n 999999
sysctl -w net.ipv4.tcp_tw_reuse=1
sysctl -w net.ipv4.tcp_tw_recycle=1
echo "Installing expect and nc"
yum -y -q install expect nc
echo "Installing MySQL"
yum -y -q localinstall MySQL*
chkconfig mysql off
