#!/bin/bash
. ../setup/include/settings
. ../setup/include/functions
. ../setup/include/settings_spammer
. include/settings_couch

setupPaswordless $COUCH_LOCAL_IP_1 $COUCH_SERVER_PASSWORD

executeScriptRemotely "scripts/couch_remote" $COUCH_LOCAL_IP_1

echo "#!/bin/bash
DB_PORT=\"$COUCH_DB_PORT\"
DB_NAME=\"$COUCH_USE_DB_NAME\" 
aDbHosts=($COUCH_LOCAL_IP_1)" > tmp/couch_settings

copySettingsToAllSpammers "tmp/couch_settings" "scripts/couchdb-v2/settings"

redEcho "Checking couchdb response. Expect Welcome..."
curl http://$COUCH_LOCAL_IP_1:$COUCH_DB_PORT